# Generated by Django 4.1.4 on 2022-12-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200522_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSuccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
